"""Created device hierarchy table

Revision ID: 0d7fcdaafd8c
Revises: 3250f8330bd7
Create Date: 2025-01-19 01:35:31.898743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7fcdaafd8c'
down_revision = '3250f8330bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=120), nullable=False),
    sa.Column('energy_demand', sa.Float(), nullable=False),
    sa.Column('energy_consumed', sa.Float(), nullable=True),
    sa.Column('number_of_requests', sa.Integer(), nullable=True),
    sa.Column('last_request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_energy')
    # ### end Alembic commands ###
