"""Add email_address column to users table

Revision ID: 3250f8330bd7
Revises: b225dd7d1ef3
Create Date: 2025-01-19 01:25:26.884423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3250f8330bd7'
down_revision = 'b225dd7d1ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
