"""Created forecast value

Revision ID: ac2920688b2b
Revises: 0d7fcdaafd8c
Create Date: 2025-01-19 01:48:29.633684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2920688b2b'
down_revision = '0d7fcdaafd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasted_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasted_value')
    # ### end Alembic commands ###
